# Generated by Django 5.2.3 on 2025-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Study in Poland with Confidence', max_length=200)),
                ('hero_subtitle', models.TextField(default='Complete support from application to integration')),
                ('hero_image', models.ImageField(blank=True, upload_to='homepage/')),
                ('hero_video_url', models.URLField(blank=True)),
                ('about_title', models.CharField(default='Why Choose Poland for Your Studies?', max_length=200)),
                ('about_content', models.TextField()),
                ('about_image', models.ImageField(blank=True, upload_to='homepage/')),
                ('services_title', models.CharField(default='Our Services', max_length=200)),
                ('services_subtitle', models.TextField(blank=True)),
                ('universities_count', models.IntegerField(default=400)),
                ('students_helped', models.IntegerField(default=1000)),
                ('success_rate', models.IntegerField(default=95)),
                ('countries_served', models.IntegerField(default=50)),
                ('cta_title', models.CharField(default='Ready to Start Your Journey?', max_length=200)),
                ('cta_subtitle', models.TextField(default='Get personalized guidance for your study abroad journey')),
                ('cta_button_text', models.CharField(default='Get Started', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Poland Study Agency', max_length=100)),
                ('tagline', models.CharField(default='Your Gateway to Education in Poland', max_length=200)),
                ('description', models.TextField(default='We help students plan and move to Poland for studies')),
                ('email', models.EmailField(default='info@polandstudyagency.com', max_length=254)),
                ('phone', models.CharField(default='+48 123 456 789', max_length=20)),
                ('address', models.TextField(default='Warsaw, Poland')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
