# Generated by Django 5.2.3 on 2025-06-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
