# Generated by Django 5.2.3 on 2025-06-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_polish', models.CharField(blank=True, max_length=255)),
                ('university_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('church', 'Church-affiliated University')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('voivodeship', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('international_students', models.BooleanField(default=True)),
                ('english_programs', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree_level', models.CharField(choices=[('bachelor', 'Bachelor Programme'), ('master', "Master's Programme"), ('long_master', "Long cycle Master's Programme"), ('doctoral', 'Doctoral studies'), ('non_degree', 'Non-degree programme')], max_length=15)),
                ('study_area', models.CharField(choices=[('agricultural', 'Agricultural, forestry and veterinary sciences'), ('arts', 'Arts'), ('biological', 'Biological sciences'), ('humanities', 'Humanities'), ('medical', 'Medical, health and sport sciences'), ('science', 'Science'), ('social', 'Social sciences'), ('technological', 'Technological sciences')], max_length=15)),
                ('language', models.CharField(choices=[('PL', 'Polish'), ('EN', 'English'), ('DE', 'German'), ('RU', 'Russian')], default='PL', max_length=2)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('ects_credits', models.IntegerField(blank=True, null=True)),
                ('tuition_fee_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('university', 'name', 'degree_level')},
            },
        ),
    ]
