# Generated by Django 5.2.3 on 2025-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, upload_to='universities/logos/'),
        ),
    ]
