# Generated by Django 5.2.3 on 2025-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_application_deadline_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
