# Generated by Django 5.2.3 on 2025-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
